[package]
name = "genetic_mkm"
version = "0.1.0"
authors = ["Jakob Fischer <JakobFischer93@gmail.com>"]

[dependencies]

rand = "0.3"
log = "0.3"
env_logger = "0.3"
chrono = "0.3"

serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
hyper = "0.11.2"
